export async function extractPageText(page){
  const content=await page.getTextContent({disableCombineTextItems:false}),items=content.items.filter(it=>typeof it.str==='string'&&it.str.trim());if(!items.length)return'';const lines=[];let current=[],lastY=null,lastX=null;
  for(const it of items){const y=Math.round(it.transform?.[5]??0),x=it.transform?.[4]??0,w=it.width??0;if(lastY!==null&&Math.abs(y-lastY)>2&&current.length){lines.push(current.join('').replace(/\s+/g,' ').trim());current=[];lastX=null}const gap=lastX!==null?x-lastX:0;if(current.length&&gap>1.7&&!/^[,.;:!?%)\]}]/.test(it.str)&&!/[([{\-–—/]$/.test(current.at(-1)))current.push(' ');current.push(it.str);lastY=y;lastX=x+w}if(current.length)lines.push(current.join('').replace(/\s+/g,' ').trim());return lines.filter(Boolean).join('\n')
}
export function cleanPages(pages,removeRepeated){const repeated=removeRepeated?detectRepeatedEdgeLines(pages):new Set();return pages.map(({page,text})=>{let raw=text.split('\n').map(s=>s.trim()).filter(Boolean);raw=expandStructuralLines(raw);const footnoteDense=countFootnoteNumbers(raw.slice(-18))>=2;const lines=raw.filter((line,idx)=>{if(isTechnicalArtifact(line))return false;const edge=idx<8||idx>=raw.length-8;if(edge&&repeated.has(normalizeRepeatedLine(line)))return false;if(edge&&isStandalonePageNumber(line))return false;if(isFootnoteNumber(line,raw,idx,footnoteDense))return false;return true});return{page,text:reflowLines(lines)}})}
function expandStructuralLines(lines){const out=[];for(let line of lines){line=line.replace(/^º\s+/,'• ');line=line.replace(/\s+(Entendendo o Conceito)\b/gi,'\n$1');line=line.replace(/\s+(?=([a-e])\)\s+)/gi,'\n');line=line.replace(/\s+(?=(?:Comentários?|Gabarito):)/gi,'\n');for(const p of line.split('\n').map(x=>x.trim()).filter(Boolean))out.push(p)}return out}
function isTechnicalArtifact(line){return /^==+\s*\d+\s*==+$/.test(line)||/^[_=]{4,}$/.test(line)}
function countFootnoteNumbers(lines){return lines.filter(x=>/^\d{1,2}$/.test(x)).length}
function isFootnoteNumber(line,lines,idx,denseBottom){if(!/^\d{1,2}$/.test(line))return false;const prev=lines[idx-1]||'',next=lines[idx+1]||'',nearCitation=/^(?:Art\.|§|CF\/|ADCT|Lei\s|LC\s)/i.test(prev)||/^(?:Art\.|§|CF\/|ADCT|Lei\s|LC\s)/i.test(next);return nearCitation||(denseBottom&&idx>=lines.length-18)}
function detectRepeatedEdgeLines(pages){const counts=new Map();for(const {text} of pages){const l=text.split('\n').map(s=>s.trim()).filter(Boolean),edge=[...l.slice(0,8),...l.slice(-8)],u=new Set(edge.map(normalizeRepeatedLine).filter(x=>x&&x.length>=3&&x.length<=150));for(const x of u)counts.set(x,(counts.get(x)||0)+1)}const threshold=Math.max(3,Math.ceil(pages.length*.28));return new Set([...counts].filter(([,n])=>n>=threshold).map(([x])=>x))}
function normalizeRepeatedLine(line){return line.toLowerCase().replace(/https?:\/\/\S+|www\.\S+/g,'<url>').replace(/\b\d{1,4}\s*(?:\/|de)\s*\d{1,4}\b/g,'<pag>').replace(/\s+/g,' ').trim()}
function isStandalonePageNumber(line){return /^\s*(?:p(?:á|a)g(?:ina)?\.?\s*)?\d{1,4}\s*(?:\/\s*\d{1,4})?\s*$/i.test(line)}
function reflowLines(lines){const out=[];let buffer='';const flush=()=>{if(buffer.trim())out.push(buffer.trim());buffer=''};for(const line of lines){if(isLikelyHeading(line)||isListLine(line)||isLegalStructure(line)||isQuestionMarker(line)){flush();out.push(line);continue}if(!buffer)buffer=line;else if(shouldJoin(buffer,line))buffer+=` ${line}`;else{flush();buffer=line}}flush();return out.join('\n\n')}
function shouldJoin(prev,next){if(isLikelyHeading(next)||isListLine(next)||isLegalStructure(next)||isQuestionMarker(next))return false;if(/[.!?;:]$/.test(prev))return false;if(/^[A-ZÁÉÍÓÚÂÊÔÃÕÇ][A-ZÁÉÍÓÚÂÊÔÃÕÇ0-9\s\-–—:]{4,}$/.test(next))return false;return true}
function isListLine(line){return /^(?:[-•▪◦]\s+|\(?[a-z]\)|\d+[.)]\s+)/i.test(line)}
function isQuestionMarker(line){return /^(?:Comentários?|Gabarito):/i.test(line)||/^\((?:CEBRASPE|CESPE|FCC|FGV|VUNESP|AOCP|IBFC|QUADRIX|FUNDATEC|IDECAN|INSTITUTO)/i.test(line)}
function isLegalStructure(line){return /^(?:art\.?\s*\d+|§\s*\d+|parágrafo\s+único|inciso\s+[ivxlcdm]+|capítulo\s+[ivxlcdm\d]+|seção\s+[ivxlcdm\d]+|subseção\s+[ivxlcdm\d]+|título\s+[ivxlcdm\d]+)/i.test(line)}
function isLikelyHeading(line){const s=line.trim();if(s.length<3||s.length>130)return false;if(/^(?:capítulo|seção|subseção|título|parte|entendendo o conceito)\b/i.test(s))return true;if(/^\d+(?:\.\d+){0,4}\s+[A-ZÁÉÍÓÚÂÊÔÃÕÇ]/.test(s))return true;if(/^[A-ZÁÉÍÓÚÂÊÔÃÕÇ0-9][A-ZÁÉÍÓÚÂÊÔÃÕÇ0-9\s\-–—:()\/]{5,}$/.test(s)&&/[A-ZÁÉÍÓÚÂÊÔÃÕÇ]/.test(s))return true;if(/^(?:[A-ZÁÉÍÓÚÂÊÔÃÕÇ][\wÀ-ÿ'’-]+\s+){1,9}[A-ZÁÉÍÓÚÂÊÔÃÕÇ][\wÀ-ÿ'’-]+$/.test(s)&&!/[.!?;]$/.test(s))return true;return false}
export function buildUnits(pages){const u=[];let id=0;for(const {page,text} of pages){const ps=text.split(/\n\s*\n+/).map(s=>s.trim()).filter(Boolean);ps.forEach((t,i)=>u.push({id:id++,text:t,page,heading:isLikelyHeading(t),pageStart:i===0}))}return u}
export function chunkUnits(units,c,meta){const bs=[];let cursor=0,overlapPrefix='';while(cursor<units.length){const start=cursor;let chars=0,i=cursor;const candidates=[];while(i<units.length){const add=units[i].text.length+2;if(chars+add>c.max&&i>start)break;chars+=add;i++;if(chars>=c.min){const next=units[i],current=units[i-1];candidates.push({index:i,count:chars,score:breakScore(next,current,chars,c)})}if(chars>=c.max)break}let end;if(i>=units.length)end=units.length;else if(candidates.length)end=selectBreakCandidate(candidates,c.target).index;else end=Math.max(start+1,i);const bodyUnits=units.slice(start,end),body=bodyUnits.map(x=>x.text).join('\n\n').trim(),sp=bodyUnits[0]?.page||1,ep=bodyUnits.at(-1)?.page||sp,num=bs.length+1;bs.push({number:num,startPage:sp,endPage:ep,body,overlapPrefix,unitIds:bodyUnits.map(x=>x.id),pages:[...new Set(bodyUnits.map(x=>x.page))]});overlapPrefix=c.overlap>0?makeOverlap(body,c.overlap):'';cursor=end}const total=bs.length;return bs.map(b=>({...b,content:buildBlockEnvelope({...b,totalBlocks:total},meta),chars:buildBlockEnvelope({...b,totalBlocks:total},meta).length}))}
function breakScore(next,current,count,c){let score=-Math.abs(count-c.target)/Math.max(c.target,1)*10;if(c.preferHeadings&&next?.heading)score+=30;if(c.preferPageBreaks&&next?.pageStart&&next.page!==current?.page)score+=18;if(current&&/[.!?;:]$/.test(current.text))score+=5;return score}
function selectBreakCandidate(c,target){const close=c.filter(x=>x.count>=target*.75&&x.count<=target*1.35),pool=close.length?close:c;return pool.reduce((a,b)=>b.score>a.score?b:a,pool[0])}
function makeOverlap(body,n){if(!body||n<=0)return'';if(body.length<=n)return body;const rough=body.length-n,p=body.indexOf('\n\n',rough);return body.slice(p!==-1&&p<body.length-80?p+2:rough).replace(/^\S*\s+/,'').trim()}
export function buildBlockEnvelope({number,startPage,endPage,overlapPrefix,body,totalBlocks},meta){const ctx=overlapPrefix?`\n[[CONTEXTO_REPETIDO_NAO_RESUMIR]]\nUse este trecho exclusivamente para compreender a continuidade. Não o resuma novamente nem o duplique, mas considere-o para interpretar corretamente o início do bloco atual.\n\n${overlapPrefix}\n[[FIM_CONTEXTO_REPETIDO]]\n`:'';return`[[PROJETO_RESUMO]]\nResumo: ${meta?.projectName||'—'}\nID_PROJETO: ${meta?.projectId||'—'}\nFonte: ${meta?.fileName||'—'}\nID_DOCUMENTO: ${meta?.sourceToken||'—'}\nBloco: ${String(number).padStart(2,'0')}/${String(totalBlocks).padStart(2,'0')}\nPáginas de origem: ${startPage}${endPage!==startPage?'–'+endPage:''}\nInstrução: este bloco pertence ao MESMO resumo dos blocos anteriores. Continue a produção sem reiniciar o material, sem repetir conteúdo já resumido e preservando a sequência lógica e estrutural já criada.\n[[FIM_PROJETO_RESUMO]]\n${ctx}\n[[CONTEUDO_FONTE]]\n${body}\n[[FIM_CONTEUDO_FONTE]]`}
export function buildAudit(totalPages,{blocks,units,pages,cleanedPages}){const covered=new Set(blocks.flatMap(b=>b.unitIds||[])),sourceChars=units.reduce((n,u)=>n+u.text.length,0),coveredChars=units.filter(u=>covered.has(u.id)).reduce((n,u)=>n+u.text.length,0),rawChars=pages.reduce((n,p)=>n+p.text.length,0),cleanChars=cleanedPages.reduce((n,p)=>n+p.text.length,0),overlapChars=blocks.reduce((n,b)=>n+(b.overlapPrefix?.length||0),0),integrity=sourceChars?coveredChars/sourceChars*100:100,nonEmpty=cleanedPages.map(p=>p.text.trim().length).filter(Boolean).sort((a,b)=>a-b),median=nonEmpty.length?nonEmpty[Math.floor(nonEmpty.length/2)]:0,lowThreshold=Math.max(40,Math.round(median*.12)),pageInfo=cleanedPages.map(p=>{const raw=pages[p.page-1]?.text.length||0,clean=p.text.trim().length,used=blocks.map((b,i)=>(b.pages||[]).includes(p.page)?i:-1).filter(i=>i>=0);let status=clean===0?'empty':clean<lowThreshold?'low':'ok';if(clean>0&&!used.length)status='unassigned';return{page:p.page,raw,clean,blocks:used,status}});return{totalPages,sourceChars,coveredChars,rawChars,cleanChars,overlapChars,integrity,lowThreshold,pageInfo}}